### ISSUE TITLE
New Bypass

### ISSUE THREAD

**Issue by daniiGP** [Cr4nkSt4r/PhasBypass#13]
the new bypass have you done it for me? you have not uploaded source code, just after responding to a copy of your code you has published this new bypass and has deleted the previous one, I have no problem deleting the code that I have published, I just want to learn c++, I sent him a message by twitter to see if you could tell me what codes must be replaced for it to work correctly, anyway I have seen that the code is also the same as an among us anticheat.

**Comment by Cr4nkSt4r** [comment]
You are just a copy paster who removes copyrights and credits, which breaks the license you agreed to, when downloading the sourcecodes.
So why should I do this for you?

The reason can be found here:
https://www.unknowncheats.me/forum/phasmophobia/502767-phasmophobia-ac-bypass.html

Same with, how the Bypass started and when.
And what code should be the same as an Among Us Anticheat?
This isn't an Anticheat.

Furthermore, the old bypass isn't deleted at all, just not maintained.
I don't want to update the Bypass with every game update, I have better stuff to do.
That's why I want the file to survive updates, which this should do.

And oc I won't share the source for that, because the Phasmophobia scene has plenty copy pasters, who copy the code, remove all credits, therefor making illegal activity with breaking the license and then sell that stuff to unknowingly customers, who could just grab the same source for free.
I don't want to support such scam, so I keep the source private and only share with friends.

**Comment by daniiGP** [comment]
okay, I have no problem removing it and I'm going to do it, another question why haven't you made that version of the bypass so that I don't have to update it every update?

**Comment by Cr4nkSt4r** [comment]
No one said you have to remove something, the only issue brought up was, that removing credits or copyright, is against the license. But your decision.

And what's your question?
Why haven't I made that version of the bypass so that you don't have to update it?
This doesn't seem to make any sense to me, please explain further.
